url: "https://johnnyo.games" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Johnny's Leaderboard" # the name of your site, e.g. ACME Corp.
